---
- name: Check if iterm2 config is differ
  shell: |
    diff <(plutil -convert binary1 -o - ./com.googlecode.iterm2.plist | md5 -q) <(md5 -q ~/Library/Preferences/com.googlecode.iterm2.plist)
  args:
    chdir: roles/iterms/files/Library/Preferences
    executable: /bin/bash
  register: diff_result
  always_run: true
  failed_when: false
  changed_when: diff_result.rc != 0
  notify:
    - Restore iterm2 configuration
