---
- name: OSX Local Provisioner
  hosts: localhost
  sudo: no
  pre_tasks:
    - stat: path=~/.ssh
      register: ssh 
  roles:
    - iterm
    # App Installations
    - brew
    - brew-cask

    # Configurations
    - git
    - dotfiles
    - xcode
    - {
      role: ssh,
      when: not ssh.stat.exists
    }
